language: python

python:
  - "3.8" # current default Python on Travis CI

# command to install dependencies
install:
  - make init

# command to run tests
script:
  - make test

env:
  - CODECOV_TOKEN=0172137f-fa27-4880-9345-56286971381e
  - CODACY_PROJECT_TOKEN=6ac17e7da7f34a1abecd0a55abd68388

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml -F Primaze
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
  # - codecov # submit coverage
